<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\MfgProcessCost;

class MfgProcessCostSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            [
                'category' => 'Product',
                'process_group' => 'Stamping',
                'process_name' => 'Stamping Rate',
                'control_point' => 'Tonnage - Stroke - Part Criteria',
                'uom' => 'Stroke',
                'rate_unit' => 'Idr / stroke',
                'min_cost_rate' => 0.0,
                'std_cost_rate' => 0.0,
                'rate_source' => 'Engineering',
            ],
            [
                'category' => 'Product',
                'process_group' => 'Non Stamping',
                'process_name' => 'RSW',
                'control_point' => 'Qty Spot',
                'uom' => 'Spot',
                'rate_unit' => 'Idr / spot',
                'min_cost_rate' => 217.6,
                'std_cost_rate' => 229.0,
                'rate_source' => 'Engineering',
            ],
            [
                'category' => 'Product',
                'process_group' => 'Non Stamping',
                'process_name' => 'PSW',
                'control_point' => 'Qty Spot',
                'uom' => 'Spot',
                'rate_unit' => 'Idr / spot',
                'min_cost_rate' => 247.0,
                'std_cost_rate' => 260.0,
                'rate_source' => 'Engineering',
            ],
            [
                'category' => 'Product',
                'process_group' => 'Non Stamping',
                'process_name' => 'SSW',
                'control_point' => 'Qty Spot',
                'uom' => 'Spot',
                'rate_unit' => 'Idr / spot',
                'min_cost_rate' => 135.9,
                'std_cost_rate' => 143.0,
                'rate_source' => 'Engineering',
            ],
            [
                'category' => 'Product',
                'process_group' => 'Non Stamping',
                'process_name' => 'Stud Weld',
                'control_point' => 'Qty Spot',
                'uom' => 'Spot',
                'rate_unit' => 'Idr / spot',
                'min_cost_rate' => 173.9,
                'std_cost_rate' => 183.0,
                'rate_source' => 'Engineering',
            ],
            [
                'category' => 'Product',
                'process_group' => 'Non Stamping',
                'process_name' => 'Shearing',
                'control_point' => 'Qty Spot',
                'uom' => 'Stroke',
                'rate_unit' => 'Idr / stroke',
                'min_cost_rate' => 397.1,
                'std_cost_rate' => 418.0,
                'rate_source' => 'Engineering',
            ],
            [
                'category' => 'Product',
                'process_group' => 'Non Stamping',
                'process_name' => 'Rivet',
                'control_point' => 'Cycle time',
                'uom' => 'second',
                'rate_unit' => 'Idr / second',
                'min_cost_rate' => 17.8,
                'std_cost_rate' => 18.7,
                'rate_source' => 'Engineering',
            ],
            [
                'category' => 'Product',
                'process_group' => 'Non Stamping',
                'process_name' => 'Clinching',
                'control_point' => 'Cycle time',
                'uom' => 'second',
                'rate_unit' => 'Idr / second',
                'min_cost_rate' => 16.9,
                'std_cost_rate' => 17.8,
                'rate_source' => 'Engineering',
            ],
            [
                'category' => 'Product',
                'process_group' => 'Non Stamping',
                'process_name' => 'Caulking',
                'control_point' => 'Cycle time',
                'uom' => 'second',
                'rate_unit' => 'Idr / second',
                'min_cost_rate' => 16.9,
                'std_cost_rate' => 17.8,
                'rate_source' => 'Engineering',
            ],
            [
                'category' => 'Product',
                'process_group' => 'Non Stamping',
                'process_name' => 'CO2',
                'control_point' => 'Length',
                'uom' => 'mm',
                'rate_unit' => 'Idr / mm',
                'min_cost_rate' => 15.0,
                'std_cost_rate' => 18.0,
                'rate_source' => 'Engineering',
            ],
            [
                'category' => 'Product',
                'process_group' => 'Others',
                'process_name' => 'ED Painting',
                'control_point' => 'Area',
                'uom' => 'mm2',
                'rate_unit' => 'Idr / mm2',
                'min_cost_rate' => 0.0,
                'std_cost_rate' => 0.0,
                'rate_source' => 'Sales',
            ],
            [
                'category' => 'Product',
                'process_group' => 'Others',
                'process_name' => 'Plating',
                'control_point' => 'Area',
                'uom' => 'mm2',
                'rate_unit' => 'Idr / mm2',
                'min_cost_rate' => 0.0,
                'std_cost_rate' => 0.0,
                'rate_source' => 'Sales',
            ],
            [
                'category' => 'Product',
                'process_group' => 'Others',
                'process_name' => 'Manual Process',
                'control_point' => 'Cycle time',
                'uom' => 'second',
                'rate_unit' => 'Idr / second',
                'min_cost_rate' => 14.5,
                'std_cost_rate' => 17.0,
                'rate_source' => 'Engineering',
            ],
            [
                'category' => 'Product',
                'process_group' => 'Others',
                'process_name' => 'QC Check',
                'control_point' => 'Cycle time',
                'uom' => 'second',
                'rate_unit' => 'Idr / second',
                'min_cost_rate' => 14.5,
                'std_cost_rate' => 17.0,
                'rate_source' => 'Engineering',
            ],
            [
                'category' => 'Tooling',
                'process_group' => 'Die Making',
                'process_name' => 'Machining CNC',
                'control_point' => 'Machine Hours',
                'uom' => 'Hour',
                'rate_unit' => 'Idr / hour',
                'min_cost_rate' => 150000.0,
                'std_cost_rate' => 175000.0,
                'rate_source' => 'Engineering',
            ],
            [
                'category' => 'Tooling',
                'process_group' => 'Die Making',
                'process_name' => 'Wire Cut',
                'control_point' => 'Cutting Hours',
                'uom' => 'Hour',
                'rate_unit' => 'Idr / hour',
                'min_cost_rate' => 120000.0,
                'std_cost_rate' => 140000.0,
                'rate_source' => 'Engineering',
            ],
            [
                'category' => 'Tooling',
                'process_group' => 'Maintenance',
                'process_name' => 'Die Repair & Trial',
                'control_point' => 'Trial Count',
                'uom' => 'Trial',
                'rate_unit' => 'Idr / trial',
                'min_cost_rate' => 500000.0,
                'std_cost_rate' => 650000.0,
                'rate_source' => 'Sales',
            ],
        ];

        foreach ($items as $item) {
            MfgProcessCost::updateOrCreate(
                [
                    'category' => $item['category'],
                    'process_group' => $item['process_group'],
                    'process_name' => $item['process_name'],
                ],
                $item
            );
        }
    }
}
